const translations = {
  zh: { tagline: '本地优先的 KU Leuven Toledo 课程材料同步工具', language: '语言', setupStep: '准备空间', setupStepHint: '选择保存位置', authStep: '登录授权', authStepHint: '连接 KU Leuven', discoverStep: '发现课程', discoverStepHint: '读取 Toledo 课程列表', syncStep: '开始同步', syncStepHint: '下载选中材料', setupTitle: '先设置学习空间', setupText: '选择 Vault、下载根目录和课程材料布局。保存后继续登录。', authTitle: '登录 Toledo', authText: '使用 KU Leuven 官方 SSO/MFA 完成授权，密码不会交给本程序。', authRequired: '等待授权', authComplete: '已完成授权', vault: 'Obsidian Vault', downloadRoot: '下载根目录', downloadHint: '例如：D:\\Courses\\2026-2027\\G0S96A Groups and Symmetries', materialsPlacement: '课程材料位置', materialsInCourse: '直接放在课程文件夹内', materialsInSubdirectory: '放在统一命名的材料子文件夹内', materialsFolderName: '材料子文件夹名称', materialsFolderHint: '例如：原始材料、Toledo materials；仅用于子文件夹模式。', choose: '选择文件夹', academicYear: '学年', allAcademicYears: '不限（全部学年）', saveSettings: '保存并继续', openDownloadRoot: '打开下载目录', coursesTitle: '选择要同步的课程', coursesText: '先读取 Toledo 返回的完整课程列表，再由你选择需要检查和更新的课程。', discover: '从 Toledo 读取课程', syncTitle: '同步课程材料', syncText: '同步只处理上面勾选且已发现的课程。', login: '登录 Toledo', syncSelected: '同步已选课程', activity: '活动监控', discovered: '已发现，可同步', notDiscovered: '尚未发现', saved: '设置已保存，请继续登录。', chooseVault: '选择 Obsidian Vault', chooseOutput: '选择下载根目录', syncing: '正在处理…', error: '错误' },
  en: { tagline: 'Local-first KU Leuven Toledo course material sync', language: 'Language', setupStep: 'Prepare space', setupStepHint: 'Choose locations', authStep: 'Sign in', authStepHint: 'Connect KU Leuven', discoverStep: 'Discover courses', discoverStepHint: 'Read Toledo’s course list', syncStep: 'Synchronize', syncStepHint: 'Download selected material', setupTitle: 'Prepare your study space', setupText: 'Choose the Vault, download root, and course-material layout before signing in.', authTitle: 'Sign in to Toledo', authText: 'Authorize with KU Leuven SSO/MFA. Your password stays on the official sign-in page.', authRequired: 'Authorization required', authComplete: 'Authorized', vault: 'Obsidian Vault', downloadRoot: 'Download root', downloadHint: 'Example: D:\\Courses\\2026-2027\\G0S96A Groups and Symmetries', materialsPlacement: 'Course-material location', materialsInCourse: 'Directly in the course folder', materialsInSubdirectory: 'In a consistently named materials subfolder', materialsFolderName: 'Materials subfolder name', materialsFolderHint: 'For example: Course materials or Raw materials. Used only in subfolder mode.', choose: 'Choose folder', academicYear: 'Academic year', allAcademicYears: 'All academic years', saveSettings: 'Save and continue', openDownloadRoot: 'Open download folder', coursesTitle: 'Choose courses to sync', coursesText: 'First read the complete course list returned by Toledo, then choose which courses to check and update.', discover: 'Read courses from Toledo', syncTitle: 'Synchronize course material', syncText: 'Only selected courses with a discovered link will be synchronized.', login: 'Sign in to Toledo', syncSelected: 'Synchronize selected', activity: 'Activity monitor', discovered: 'Discovered · ready to sync', notDiscovered: 'Not discovered', saved: 'Settings saved. Continue with sign-in.', chooseVault: 'Choose Obsidian Vault', chooseOutput: 'Choose download root', syncing: 'Working…', error: 'Error' },
  nl: { tagline: 'Lokale synchronisatie van KU Leuven Toledo-cursusmateriaal', language: 'Taal', setupStep: 'Ruimte voorbereiden', setupStepHint: 'Locaties kiezen', authStep: 'Aanmelden', authStepHint: 'KU Leuven verbinden', discoverStep: 'Cursussen zoeken', discoverStepHint: 'Toledo-cursussen lezen', syncStep: 'Synchroniseren', syncStepHint: 'Geselecteerd materiaal downloaden', setupTitle: 'Je studieruimte voorbereiden', setupText: 'Kies de Vault, downloadhoofdmap en cursusindeling voordat je aanmeldt.', authTitle: 'Aanmelden bij Toledo', authText: 'Machtig met KU Leuven SSO/MFA. Je wachtwoord blijft op de officiële aanmeldpagina.', authRequired: 'Aanmelding vereist', authComplete: 'Aangemeld', vault: 'Obsidian Vault', downloadRoot: 'Downloadhoofdmap', downloadHint: 'Voorbeeld: D:\\Courses\\2026-2027\\G0S96A Groups and Symmetries', materialsPlacement: 'Locatie van cursusmateriaal', materialsInCourse: 'Rechtstreeks in de cursusmap', materialsInSubdirectory: 'In een uniform benoemde materiaalmap', materialsFolderName: 'Naam van materiaalmap', materialsFolderHint: 'Bijvoorbeeld: Cursusmateriaal of Bronnen. Alleen gebruikt in mapmodus.', choose: 'Map kiezen', academicYear: 'Academiejaar', allAcademicYears: 'Alle academiejaren', saveSettings: 'Opslaan en doorgaan', openDownloadRoot: 'Downloadmap openen', coursesTitle: 'Cursussen kiezen', coursesText: 'Lees eerst de volledige cursuslijst van Toledo en kies daarna welke cursussen je wilt controleren en bijwerken.', discover: 'Cursussen uit Toledo lezen', syncTitle: 'Cursusmateriaal synchroniseren', syncText: 'Alleen geselecteerde cursussen met een gevonden link worden gesynchroniseerd.', login: 'Aanmelden bij Toledo', syncSelected: 'Geselecteerde synchroniseren', activity: 'Activiteitsmonitor', discovered: 'Gevonden · klaar voor synchronisatie', notDiscovered: 'Niet gevonden', saved: 'Instellingen opgeslagen. Ga door met aanmelden.', chooseVault: 'Obsidian Vault kiezen', chooseOutput: 'Downloadhoofdmap kiezen', syncing: 'Bezig…', error: 'Fout' }
};
Object.assign(translations.zh, { automationTitle: '自动更新', automationText: '设置应用启动和运行期间的自动检查。', autoStart: '开机时启动 Toledo Sync', autoCheckOnLaunch: '启动时检查并同步课程更新', periodicCheck: '周期性检查', periodicOff: '关闭', periodic30: '每 30 分钟', periodic60: '每小时', periodic360: '每 6 小时', periodic1440: '每天' });
Object.assign(translations.en, { automationTitle: 'Automatic updates', automationText: 'Choose whether checks run when the app starts or while it stays open.', autoStart: 'Start Toledo Sync when Windows starts', autoCheckOnLaunch: 'Check and synchronize updates on launch', periodicCheck: 'Scheduled checks', periodicOff: 'Off', periodic30: 'Every 30 minutes', periodic60: 'Every hour', periodic360: 'Every 6 hours', periodic1440: 'Every day' });
Object.assign(translations.nl, { automationTitle: 'Automatische updates', automationText: 'Kies of controles starten bij het openen of tijdens het gebruik.', autoStart: 'Toledo Sync starten wanneer Windows start', autoCheckOnLaunch: 'Updates controleren en synchroniseren bij het openen', periodicCheck: 'Geplande controles', periodicOff: 'Uit', periodic30: 'Elke 30 minuten', periodic60: 'Elk uur', periodic360: 'Elke 6 uur', periodic1440: 'Elke dag' });
Object.assign(translations.zh, { checkUpdates: '检查更新', applyUpdates: '下载已检查更新', checkCourse: '检查此课程更新', summaryNew: '新增', summaryUnchanged: '未变化', summaryModified: '本地已修改', summaryErrors: '错误', summaryNone: '暂无可下载更新', summaryNotDiscovered: '尚未发现课程链接' });
Object.assign(translations.en, { checkUpdates: 'Check for updates', applyUpdates: 'Download checked updates', checkCourse: 'Check this course', summaryNew: 'new', summaryUnchanged: 'unchanged', summaryModified: 'locally modified', summaryErrors: 'errors', summaryNone: 'No downloadable updates', summaryNotDiscovered: 'Course link not discovered' });
Object.assign(translations.nl, { checkUpdates: 'Op updates controleren', applyUpdates: 'Gecontroleerde updates downloaden', checkCourse: 'Deze cursus controleren', summaryNew: 'nieuw', summaryUnchanged: 'ongewijzigd', summaryModified: 'lokaal gewijzigd', summaryErrors: 'fouten', summaryNone: 'Geen downloadbare updates', summaryNotDiscovered: 'Cursuslink niet gevonden' });
Object.assign(translations.zh, { tabSpace: '学习空间', tabCourses: '登录与课程', tabUpdates: '更新中心', tabAutomation: '自动化', updateSafetyTitle: '更新是可预览的', updateSafetyText: '先检查会读取远程文件并比较内容，不会写入课程材料。本地修改文件会保留，应用时以带哈希的副本保存远程版本。' });
Object.assign(translations.en, { tabSpace: 'Study space', tabCourses: 'Sign in & courses', tabUpdates: 'Update center', tabAutomation: 'Automation', updateSafetyTitle: 'Updates are previewable', updateSafetyText: 'Check first reads remote files and compares content without writing course material. Local edits are kept; applying an update saves the remote version beside them with a hash.' });
Object.assign(translations.nl, { tabSpace: 'Studieruimte', tabCourses: 'Aanmelden & vakken', tabUpdates: 'Updatecentrum', tabAutomation: 'Automatisering', updateSafetyTitle: 'Updates zijn vooraf te bekijken', updateSafetyText: 'Eerst controleren leest externe bestanden en vergelijkt de inhoud zonder cursusmateriaal te schrijven. Lokale wijzigingen blijven behouden; toepassen bewaart de externe versie met een hash ernaast.' });
Object.assign(translations.zh, { fileTreeTitle: '更新后的文件树', fileTreeEmpty: '检查更新后将在这里显示完整文件树。', treeAllCourses: '所有已检查课程', treeNew: '新增', treeUnchanged: '未变化', treeModified: '本地修改保护副本' });
Object.assign(translations.en, { fileTreeTitle: 'Resulting file tree', fileTreeEmpty: 'The complete file tree will appear here after checking for updates.', treeAllCourses: 'All checked courses', treeNew: 'new', treeUnchanged: 'unchanged', treeModified: 'local edit preserved as copy' });
Object.assign(translations.nl, { fileTreeTitle: 'Bestandsstructuur na update', fileTreeEmpty: 'De volledige bestandsstructuur verschijnt hier na het controleren.', treeAllCourses: 'Alle gecontroleerde vakken', treeNew: 'nieuw', treeUnchanged: 'ongewijzigd', treeModified: 'lokale wijziging als kopie behouden' });
Object.assign(translations.zh, { verificationMode: '本地校验方式', verificationSha256: 'SHA-256（内容哈希）', verificationFilename: '文件名和路径', verificationHint: 'SHA-256 能识别内容变化并保护本地修改；文件名模式只按文件名和路径判断。' });
Object.assign(translations.en, { verificationMode: 'Local verification', verificationSha256: 'SHA-256 (content hash)', verificationFilename: 'Filename and path', verificationHint: 'SHA-256 detects content changes and protects local edits; filename mode compares only names and paths.' });
Object.assign(translations.nl, { verificationMode: 'Lokale controle', verificationSha256: 'SHA-256 (inhoudshash)', verificationFilename: 'Bestandsnaam en pad', verificationHint: 'SHA-256 detecteert inhoudswijzigingen en beschermt lokale bewerkingen; naammodus vergelijkt alleen namen en paden.' });
let locale = localStorage.getItem('toledo-locale') || (navigator.language.startsWith('nl') ? 'nl' : navigator.language.startsWith('zh') ? 'zh' : 'en');
let state = { config: null, busy: false, authenticated: false, discoveryDone: false, activityLog: [], updatePlan: null };
const $ = (selector) => document.querySelector(selector);
const t = (key) => translations[locale][key] || key;
function setText() { document.documentElement.lang = locale; document.title = 'Toledo Sync'; document.querySelectorAll('[data-i18n]').forEach((node) => { node.textContent = t(node.dataset.i18n); }); }
function updateMaterialsFolderVisibility() { $('#materialsFolderField').hidden = $('#materialsPlacement').value !== 'subdirectory'; }
function status(message) { $('#status').textContent = message; }
function result(value) { const summary = typeof value === 'string' ? value : JSON.stringify(value, null, 2); $('#results').textContent = `${state.activityLog.join('\n')}${state.activityLog.length ? '\n\n' : ''}${summary}`; $('#results').scrollTop = $('#results').scrollHeight; }
function appendActivity(message) { const stamp = new Date().toLocaleTimeString(); state.activityLog.push(`[${stamp}] ${message}`); if (state.activityLog.length > 250) state.activityLog.shift(); $('#results').textContent = state.activityLog.join('\n'); $('#results').scrollTop = $('#results').scrollHeight; }
function summaryText(summary) { if (!summary) return ''; if (summary.status === 'not-discovered') return t('summaryNotDiscovered'); const bits = []; if (summary.newCount) bits.push(`${summary.newCount} ${t('summaryNew')}`); if (summary.unchangedCount) bits.push(`${summary.unchangedCount} ${t('summaryUnchanged')}`); if (summary.localModifiedCount) bits.push(`${summary.localModifiedCount} ${t('summaryModified')}`); if (summary.errorCount) bits.push(`${summary.errorCount} ${t('summaryErrors')}`); return bits.length ? bits.join(' · ') : t('summaryNone'); }
function renderFileTree() {
  const select = $('#treeCourse'); const tree = $('#fileTree'); const summaries = Array.isArray(state.updatePlan) ? state.updatePlan : [];
  const previous = select.value; select.replaceChildren(); select.append(new Option(t('treeAllCourses'), 'all'));
  summaries.forEach((summary) => select.append(new Option(`${summary.code} ${summary.title}`, summary.code)));
  select.value = summaries.some((summary) => summary.code === previous) || previous === 'all' ? previous : 'all';
  const visible = select.value === 'all' ? summaries : summaries.filter((summary) => summary.code === select.value);
  if (!visible.length) { tree.textContent = t('fileTreeEmpty'); return; }
  const lines = [];
  for (const summary of visible) {
    lines.push(`📁 ${summary.code} ${summary.title}`);
    const files = [...(summary.files || [])].filter((file) => file.file).sort((a, b) => a.file.localeCompare(b.file));
    files.forEach((file, index) => {
      const marker = file.status === 'new' ? '＋' : file.status === 'local-modified' ? '↪' : file.status === 'unchanged' ? '·' : '×';
      lines.push(`${index === files.length - 1 ? '└──' : '├──'} ${marker} ${file.file}  [${file.status === 'new' ? t('treeNew') : file.status === 'local-modified' ? t('treeModified') : file.status === 'unchanged' ? t('treeUnchanged') : file.status}]`);
    });
  }
  tree.textContent = lines.join('\n');
}
function selectedCourseCodes() { return (state.config?.courses || []).filter((course) => course.selected).map((course) => course.code); }
function setBusy(value) { state.busy = value; document.querySelectorAll('button:not(.tab)').forEach((button) => { button.disabled = value; }); if (!value && state.config) render(); }
function render() {
  const config = state.config; $('#vaultPath').value = config?.vaultPath || ''; $('#outputRoot').value = config?.outputRoot || ''; $('#materialsPlacement').value = config?.materialsPlacement || 'subdirectory'; $('#materialsFolderName').value = config?.materialsFolderName || 'Materials'; $('#verificationMode').value = config?.verificationMode || 'sha256'; $('#autoStart').checked = Boolean(config?.autoStart); $('#autoCheckOnLaunch').checked = Boolean(config?.autoCheckOnLaunch); $('#periodicCheckMinutes').value = String(config?.periodicCheckMinutes || 0); updateMaterialsFolderVisibility();
  const hasConfig = Boolean(config?.vaultPath && config?.outputRoot); const hasDiscovered = state.discoveryDone && (config?.courses || []).some((course) => course.discovered); const hasSelected = (config?.courses || []).some((course) => course.selected && course.discovered); const hasPlan = Array.isArray(state.updatePlan); const hasActionablePlan = hasPlan && state.updatePlan.some((summary) => summary.newCount || summary.localModifiedCount);
  $('#authState').textContent = state.authenticated ? t('authComplete') : t('authRequired'); $('#authState').classList.toggle('complete', state.authenticated);
  $('#login').disabled = !hasConfig || state.busy; $('#discover').disabled = !hasConfig || !state.authenticated || state.busy; $('#checkUpdates').disabled = !hasSelected || !state.authenticated || state.busy; $('#applyUpdates').disabled = !hasActionablePlan || !state.authenticated || state.busy;
  $('#stepSetup').classList.toggle('complete', hasConfig); $('#stepAuth').classList.toggle('complete', state.authenticated); $('#stepDiscover').classList.toggle('complete', hasDiscovered); $('#stepSync').classList.toggle('active', hasSelected && state.discoveryDone); $('#discoverCard').classList.toggle('locked', !state.authenticated); $('#syncCard').classList.toggle('locked', !hasSelected || !state.discoveryDone);
  renderFileTree(); const list = $('#courses'); list.replaceChildren();
  for (const course of config?.courses || []) {
    const node = $('#courseTemplate').content.firstElementChild.cloneNode(true); const checkbox = node.querySelector('input'); checkbox.checked = course.selected; checkbox.disabled = !state.discoveryDone || !course.discovered; checkbox.dataset.code = course.code;
    checkbox.addEventListener('change', () => {
      // Keep the in-memory selection before rebuilding the course cards.
      // Otherwise render() immediately restored the value from the old config.
      course.selected = checkbox.checked;
      state.updatePlan = null;
      render();
    });
    node.querySelector('strong').textContent = course.code; node.querySelector('.course-main span').textContent = course.title;
    node.querySelector('.update-summary').textContent = summaryText(state.updatePlan?.find((summary) => summary.code === course.code));
    const availability = node.querySelector('.availability'); availability.textContent = course.discovered ? t('discovered') : t('notDiscovered'); availability.classList.toggle('available', course.discovered);
    const syncButton = node.querySelector('button'); syncButton.disabled = !state.authenticated || !state.discoveryDone || !course.discovered || state.busy; syncButton.title = `${t('checkCourse')}: ${course.code}`; syncButton.addEventListener('click', (event) => { event.preventDefault(); event.stopPropagation(); run(async () => { const value = await window.toledo.checkUpdates(course.code, selectedCourseCodes()); state.updatePlan = value.summaries; render(); return value.summaries; }); });
    list.append(node);
  }
}
async function save() {
  const selectedCodes = [...document.querySelectorAll('#courses input:checked')].map((box) => box.dataset.code);
  state.config = await window.toledo.saveConfig({ vaultPath: $('#vaultPath').value, outputRoot: $('#outputRoot').value, materialsPlacement: $('#materialsPlacement').value, materialsFolderName: $('#materialsFolderName').value.trim(), verificationMode: $('#verificationMode').value, autoStart: $('#autoStart').checked, autoCheckOnLaunch: $('#autoCheckOnLaunch').checked, periodicCheckMinutes: Number($('#periodicCheckMinutes').value), selectedCodes }); state.authenticated = state.config.authenticated;
  render(); status(t('saved'));
}
async function run(operation) { try { setBusy(true); appendActivity(t('syncing')); status(t('syncing')); const value = await operation(); result(value); } catch (error) { appendActivity(`${t('error')}: ${error.message}`); status(`${t('error')}: ${error.message}`); } finally { setBusy(false); } }
setText();
$('#language').value = locale; $('#language').addEventListener('change', (event) => { locale = event.target.value; localStorage.setItem('toledo-locale', locale); setText(); render(); });
document.querySelectorAll('.tab').forEach((tab) => tab.addEventListener('click', () => {
  document.querySelectorAll('.tab').forEach((item) => item.classList.toggle('active', item === tab));
  document.querySelectorAll('.tab-panel').forEach((panel) => panel.classList.toggle('active', panel.dataset.panel === tab.dataset.tab));
}));
$('#materialsPlacement').addEventListener('change', updateMaterialsFolderVisibility);
$('#chooseVault').addEventListener('click', async () => { const folder = await window.toledo.chooseDirectory(t('chooseVault')); if (folder) $('#vaultPath').value = folder; });
$('#chooseOutput').addEventListener('click', async () => { const folder = await window.toledo.chooseDirectory(t('chooseOutput')); if (folder) $('#outputRoot').value = folder; });
$('#save').addEventListener('click', () => run(save)); $('#login').addEventListener('click', () => run(async () => { const value = await window.toledo.login(); state.authenticated = true; render(); return value; }));
$('#saveAutomation').addEventListener('click', () => run(save));
$('#treeCourse').addEventListener('change', renderFileTree);
$('#discover').addEventListener('click', () => run(async () => { const value = await window.toledo.discover(); state.config = value.config; state.discoveryDone = true; state.updatePlan = null; render(); return value.matches; }));
$('#checkUpdates').addEventListener('click', () => run(async () => { const value = await window.toledo.checkUpdates(null, selectedCourseCodes()); state.updatePlan = value.summaries; render(); return value.summaries; })); $('#applyUpdates').addEventListener('click', () => run(async () => { const value = await window.toledo.applyUpdates(null, selectedCourseCodes()); state.updatePlan = value.summaries; render(); return value.summaries; })); $('#openRoot').addEventListener('click', () => run(() => window.toledo.openPath($('#outputRoot').value)));
if (!window.toledo) {
  status('Desktop bridge could not start. Please reinstall the application.');
} else {
  window.toledo.onEvent((event) => { appendActivity(event.message); status(event.message); });
  (async () => { const initial = await window.toledo.initial(); $('#platform').textContent = initial.platform === 'win32' ? 'Windows' : initial.platform; state.config = initial.config; state.authenticated = Boolean(initial.config?.authenticated); render(); })();
}
