const translations = {
  zh: { tagline: '本地优先的 KU Leuven Toledo 课程材料同步工具', language: '语言', setupStep: '准备空间', setupStepHint: '选择保存位置', authStep: '登录授权', authStepHint: '连接 KU Leuven', discoverStep: '发现课程', discoverStepHint: '读取本学年课程', syncStep: '开始同步', syncStepHint: '下载选中材料', setupTitle: '先设置学习空间', setupText: '选择 Vault、下载根目录和课程材料布局。保存后继续登录。', authTitle: '登录 Toledo', authText: '使用 KU Leuven 官方 SSO/MFA 完成授权，密码不会交给本程序。', authRequired: '等待授权', authComplete: '已完成授权', vault: 'Obsidian Vault', downloadRoot: '下载根目录', downloadHint: '例如：D:\\Courses\\2026-2027\\G0S96A Groups and Symmetries', materialsPlacement: '课程材料位置', materialsInCourse: '直接放在课程文件夹内', materialsInSubdirectory: '放在统一命名的材料子文件夹内', materialsFolderName: '材料子文件夹名称', materialsFolderHint: '例如：原始材料、Toledo materials；仅用于子文件夹模式。', choose: '选择文件夹', academicYear: '学年', saveSettings: '保存并继续', openDownloadRoot: '打开下载目录', coursesTitle: '选择要同步的课程', coursesText: '先点击“发现全部课程”，然后勾选需要同步的课程。', discover: '发现全部课程', syncTitle: '同步课程材料', syncText: '同步只处理上面勾选且已发现的课程。', login: '登录 Toledo', syncSelected: '同步已选课程', activity: '活动监控', discovered: '已发现，可同步', notDiscovered: '尚未发现', saved: '设置已保存，请继续登录。', chooseVault: '选择 Obsidian Vault', chooseOutput: '选择下载根目录', syncing: '正在处理…', error: '错误' },
  en: { tagline: 'Local-first KU Leuven Toledo course material sync', language: 'Language', setupStep: 'Prepare space', setupStepHint: 'Choose locations', authStep: 'Sign in', authStepHint: 'Connect KU Leuven', discoverStep: 'Discover courses', discoverStepHint: 'Read this year’s list', syncStep: 'Synchronize', syncStepHint: 'Download selected material', setupTitle: 'Prepare your study space', setupText: 'Choose the Vault, download root, and course-material layout before signing in.', authTitle: 'Sign in to Toledo', authText: 'Authorize with KU Leuven SSO/MFA. Your password stays on the official sign-in page.', authRequired: 'Authorization required', authComplete: 'Authorized', vault: 'Obsidian Vault', downloadRoot: 'Download root', downloadHint: 'Example: D:\\Courses\\2026-2027\\G0S96A Groups and Symmetries', materialsPlacement: 'Course-material location', materialsInCourse: 'Directly in the course folder', materialsInSubdirectory: 'In a consistently named materials subfolder', materialsFolderName: 'Materials subfolder name', materialsFolderHint: 'For example: Course materials or Raw materials. Used only in subfolder mode.', choose: 'Choose folder', academicYear: 'Academic year', saveSettings: 'Save and continue', openDownloadRoot: 'Open download folder', coursesTitle: 'Choose courses to sync', coursesText: 'Discover all courses first, then select the ones to synchronize.', discover: 'Discover all courses', syncTitle: 'Synchronize course material', syncText: 'Only selected courses with a discovered link will be synchronized.', login: 'Sign in to Toledo', syncSelected: 'Synchronize selected', activity: 'Activity monitor', discovered: 'Discovered · ready to sync', notDiscovered: 'Not discovered', saved: 'Settings saved. Continue with sign-in.', chooseVault: 'Choose Obsidian Vault', chooseOutput: 'Choose download root', syncing: 'Working…', error: 'Error' },
  nl: { tagline: 'Lokale synchronisatie van KU Leuven Toledo-cursusmateriaal', language: 'Taal', setupStep: 'Ruimte voorbereiden', setupStepHint: 'Locaties kiezen', authStep: 'Aanmelden', authStepHint: 'KU Leuven verbinden', discoverStep: 'Cursussen zoeken', discoverStepHint: 'Lijst van dit jaar lezen', syncStep: 'Synchroniseren', syncStepHint: 'Geselecteerd materiaal downloaden', setupTitle: 'Je studieruimte voorbereiden', setupText: 'Kies de Vault, downloadhoofdmap en cursusindeling voordat je aanmeldt.', authTitle: 'Aanmelden bij Toledo', authText: 'Machtig met KU Leuven SSO/MFA. Je wachtwoord blijft op de officiële aanmeldpagina.', authRequired: 'Aanmelding vereist', authComplete: 'Aangemeld', vault: 'Obsidian Vault', downloadRoot: 'Downloadhoofdmap', downloadHint: 'Voorbeeld: D:\\Courses\\2026-2027\\G0S96A Groups and Symmetries', materialsPlacement: 'Locatie van cursusmateriaal', materialsInCourse: 'Rechtstreeks in de cursusmap', materialsInSubdirectory: 'In een uniform benoemde materiaalmap', materialsFolderName: 'Naam van materiaalmap', materialsFolderHint: 'Bijvoorbeeld: Cursusmateriaal of Bronnen. Alleen gebruikt in mapmodus.', choose: 'Map kiezen', academicYear: 'Academiejaar', saveSettings: 'Opslaan en doorgaan', openDownloadRoot: 'Downloadmap openen', coursesTitle: 'Cursussen kiezen', coursesText: 'Zoek eerst alle cursussen en selecteer daarna wat je wilt synchroniseren.', discover: 'Alle cursussen zoeken', syncTitle: 'Cursusmateriaal synchroniseren', syncText: 'Alleen geselecteerde cursussen met een gevonden link worden gesynchroniseerd.', login: 'Aanmelden bij Toledo', syncSelected: 'Geselecteerde synchroniseren', activity: 'Activiteitsmonitor', discovered: 'Gevonden · klaar voor synchronisatie', notDiscovered: 'Niet gevonden', saved: 'Instellingen opgeslagen. Ga door met aanmelden.', chooseVault: 'Obsidian Vault kiezen', chooseOutput: 'Downloadhoofdmap kiezen', syncing: 'Bezig…', error: 'Fout' }
};
let locale = localStorage.getItem('toledo-locale') || (navigator.language.startsWith('nl') ? 'nl' : navigator.language.startsWith('zh') ? 'zh' : 'en');
let state = { config: null, busy: false, authenticated: false, discoveryDone: false, activityLog: [] };
const $ = (selector) => document.querySelector(selector);
const t = (key) => translations[locale][key] || key;
function setText() { document.documentElement.lang = locale; document.title = 'Toledo Sync'; document.querySelectorAll('[data-i18n]').forEach((node) => { node.textContent = t(node.dataset.i18n); }); }
function updateMaterialsFolderVisibility() { $('#materialsFolderField').hidden = $('#materialsPlacement').value !== 'subdirectory'; }
function status(message) { $('#status').textContent = message; }
function result(value) { const summary = typeof value === 'string' ? value : JSON.stringify(value, null, 2); $('#results').textContent = `${state.activityLog.join('\n')}${state.activityLog.length ? '\n\n' : ''}${summary}`; $('#results').scrollTop = $('#results').scrollHeight; }
function appendActivity(message) { const stamp = new Date().toLocaleTimeString(); state.activityLog.push(`[${stamp}] ${message}`); if (state.activityLog.length > 250) state.activityLog.shift(); $('#results').textContent = state.activityLog.join('\n'); $('#results').scrollTop = $('#results').scrollHeight; }
function setBusy(value) { state.busy = value; document.querySelectorAll('button').forEach((button) => { button.disabled = value; }); if (!value && state.config) render(); }
function render() {
  const config = state.config; $('#vaultPath').value = config?.vaultPath || ''; $('#outputRoot').value = config?.outputRoot || ''; $('#materialsPlacement').value = config?.materialsPlacement || 'subdirectory'; $('#materialsFolderName').value = config?.materialsFolderName || 'Materials'; const year = config?.academicYear || '2026-2027'; if (![...$('#academicYear').options].some((option) => option.value === year)) $('#academicYear').add(new Option(year, year)); $('#academicYear').value = year; updateMaterialsFolderVisibility();
  const hasConfig = Boolean(config?.vaultPath && config?.outputRoot); const hasDiscovered = state.discoveryDone && (config?.courses || []).some((course) => course.discovered); const hasSelected = (config?.courses || []).some((course) => course.selected && course.discovered);
  $('#authState').textContent = state.authenticated ? t('authComplete') : t('authRequired'); $('#authState').classList.toggle('complete', state.authenticated);
  $('#login').disabled = !hasConfig || state.busy; $('#discover').disabled = !hasConfig || !state.authenticated || state.busy; $('#sync').disabled = !hasSelected || !state.authenticated || state.busy;
  $('#stepSetup').classList.toggle('complete', hasConfig); $('#stepAuth').classList.toggle('complete', state.authenticated); $('#stepDiscover').classList.toggle('complete', hasDiscovered); $('#stepSync').classList.toggle('active', hasSelected && state.discoveryDone); $('#discoverCard').classList.toggle('locked', !state.authenticated); $('#syncCard').classList.toggle('locked', !hasSelected || !state.discoveryDone);
  const list = $('#courses'); list.replaceChildren();
  for (const course of config?.courses || []) {
    const node = $('#courseTemplate').content.firstElementChild.cloneNode(true); const checkbox = node.querySelector('input'); checkbox.checked = course.selected; checkbox.disabled = !state.discoveryDone || !course.discovered; checkbox.dataset.code = course.code;
    node.querySelector('strong').textContent = course.code; node.querySelector('.course-main span').textContent = course.title;
    const availability = node.querySelector('.availability'); availability.textContent = course.discovered ? t('discovered') : t('notDiscovered'); availability.classList.toggle('available', course.discovered);
    const syncButton = node.querySelector('button'); syncButton.disabled = !state.authenticated || !state.discoveryDone || !course.discovered || state.busy; syncButton.title = `${t('syncSelected')}: ${course.code}`; syncButton.addEventListener('click', () => run(() => window.toledo.sync(course.code)));
    list.append(node);
  }
}
async function save() {
  const selectedCodes = [...document.querySelectorAll('#courses input:checked')].map((box) => box.dataset.code);
  state.config = await window.toledo.saveConfig({ vaultPath: $('#vaultPath').value, outputRoot: $('#outputRoot').value, materialsPlacement: $('#materialsPlacement').value, materialsFolderName: $('#materialsFolderName').value.trim(), academicYear: $('#academicYear').value.trim(), selectedCodes }); state.authenticated = state.config.authenticated;
  render(); status(t('saved'));
}
async function run(operation) { try { setBusy(true); appendActivity(t('syncing')); status(t('syncing')); const value = await operation(); result(value); } catch (error) { appendActivity(`${t('error')}: ${error.message}`); status(`${t('error')}: ${error.message}`); } finally { setBusy(false); } }
setText();
$('#language').value = locale; $('#language').addEventListener('change', (event) => { locale = event.target.value; localStorage.setItem('toledo-locale', locale); setText(); render(); });
$('#materialsPlacement').addEventListener('change', updateMaterialsFolderVisibility);
$('#chooseVault').addEventListener('click', async () => { const folder = await window.toledo.chooseDirectory(t('chooseVault')); if (folder) $('#vaultPath').value = folder; });
$('#chooseOutput').addEventListener('click', async () => { const folder = await window.toledo.chooseDirectory(t('chooseOutput')); if (folder) $('#outputRoot').value = folder; });
$('#save').addEventListener('click', () => run(save)); $('#login').addEventListener('click', () => run(async () => { const value = await window.toledo.login(); state.authenticated = true; render(); return value; }));
$('#discover').addEventListener('click', () => run(async () => { const value = await window.toledo.discover(); state.config = value.config; state.discoveryDone = true; render(); return value.matches; }));
$('#sync').addEventListener('click', () => run(() => window.toledo.sync(null))); $('#openRoot').addEventListener('click', () => run(() => window.toledo.openPath($('#outputRoot').value)));
if (!window.toledo) {
  status('Desktop bridge could not start. Please reinstall the application.');
} else {
  window.toledo.onEvent((event) => { appendActivity(event.message); status(event.message); });
  (async () => { const initial = await window.toledo.initial(); $('#platform').textContent = initial.platform === 'win32' ? 'Windows' : initial.platform; state.config = initial.config; state.authenticated = Boolean(initial.config?.authenticated); render(); })();
}
